EnvironmentClass_other: Environment class for the cluster.
Schedulers: The number of schedulers that you want to run in your environment. v2.0.2 and above accepts `2` - `5`, default `2`. v1.10.12 accepts `1`.
MinWorkers: The minimum number of workers that you want to run in your environment.
MaxWorkers: The maximum number of workers that can be automatically scaled up. Value need to be between `1` and `25`.
AirflowConfigurationOptions_str: |
  Specify parameters to override airflow options.
  Sample Value can be as below
  ```js
  {
    "core.log_format": "[%%(asctime)s] {{%%(filename)s:%%(lineno)d}} %%(levelname)s - %%(message)s"
  }
  ```
