EnableSecurityHub: Enable AWS Security Hub in any region where there is infrastructure managed by DuploCloud.
EnableAllSecurityHubRegions: Enable AWS Security Hub in all AWS regions managed
  by DuploCloud.
SecurityHubMembershipType: |
  Enable or disable multi-account AWS Security Hub:

  - **Local**: Disable any multi-account administration by this account in AWS Security Hub.
  - **Centralized (in this account)**: Allow this account to manage other accounts in AWS Security Hub.
  - **Centralized (in another account)**: Allow this account to be managed by another DuploCloud in AWS Security Hub. Disable any multi-account administration by this account in AWS Security Hub.
SecurityHubAdminAccount: The AWS Account ID of the Security Hub administrator
  account.
ConfigLogBucketType: |
  Enable or disable cross-account AWS Config logging:

  - **Local**: AWS Config will log to an S3 bucket owned by this account.
  - **Centralized (in this account)**: AWS Config will log to an S3 bucket owned by this account. Allow AWS Config in other accounts to log to this same bucket.
  - **Centralized (in another account)**: AWS Config will log to an S3 bucket owned by another account.
ConfigLogBucketName: The S3 bucket name that AWS Config will log to.
EnableGuardDuty: Enable AWS Guard Duty in all AWS regions managed by DuploCloud.
EnableInspector: Enable AWS Inspector in any region where there is infrastructure
  managed by DuploCloud.
EnableAllInspectorRegions: Enable AWS Inspector in all AWS regions managed by
  DuploCloud.
IgnoreDefaultEbsEncryption: |
  Normally, DuploCloud enables EBS Default Encryption for all regions in which you deploy infrastructure.

  When this box is checked, DuploCloud will ignore the EBS Default Encryption settings when creating any new infrastructure.

  However, you can still edit the `EBS Encryption by Default` setting for your infrastructure - to enable EBS encryption by default, for the entire AWS region.
EnablePasswordPolicy: |
  Enable an account-level IAM User password policy:

  - Minimum password length is 14 characters
  - Require at least one uppercase letter from Latin alphabet (A-Z)
  - Require at least one lowercase letter from Latin alphabet (a-z)
  - Require at least one number
  - Require at least one non-alphanumeric character (! @ # $ % ^ & * ( ) _ + - = [ ] { } | ')
  - Password expires in 90 day(s)
  - Allow users to change their own password
  - Remember last 24 password(s) and prevent reuse
EnableCloudTrail: |
  Enable a multi-region CloudTrail for this AWS account.

  Enabling this feature will tell DuploCloud to:

  - Create and manage a multi-region CloudTrail in this AWS account
  - Create a CloudWatch log group named `/cloudtrail/duplo` that receives CloudTrail events
  - Create and manage an S3 bucket that receives CloudTrail log files
CloudTrailLogBucketType: |
  Enable or disable cross-account AWS CloudTrail logging:

  - **Local**: AWS CloudTrail will log to an S3 bucket owned by this account.
  - **Centralized (in this account)**: AWS CloudTrail will log to an S3 bucket owned by this account. Allow AWS CloudTrail in other accounts to log to this same bucket.
  - **Centralized (in another account)**: AWS CloudTrail will log to an S3 bucket owned by another account.
CloudTrailLogBucketAccount: The AWS Account where AWS CloudTrail S3 logs will
  reside in.
CloudTrailLogBucketName: The S3 bucket name that AWS CloudTrail will log to.
CloudTrailLogBucketKmsKeyId: The KMS Key ID that AWS CloudTrail S3 logs will use.
EnableVpcFlowLogs: Enable VPC flow logs for all VPCs created by DuploCloud.
DeleteDefaultVpcs: Delete default VPCs in all AWS regions managed by DuploCloud.
DeleteDefaultNaclRules: Delete default NACL rules for all VPCs created by DuploCloud.
RevokeDefaultSgRules: Revoke default Security Group rules for all VPCs created
  by DuploCloud.
EnableCisCloudTrailCloudWatchAlarms: |
  Enables CIS CloudTrail CloudWatch Alarms in all AWS regions managed by DuploCloud.

  Enabling this feature and specifying an email address to receive alerts will satisfy AWS CIS controls 3.1 through 3.14.
CisCloudWatchAlarmNotificationEmail: |
  Specifies an email address that should receive the CIS CloudTrail CloudWatch Alarms.

  In order to satisfy AWS CIS controls 3.1 through 3.14, the email recipient must first confirm the subscription to receive the alerts from AWS.